const istwaYo = {
    // 🇭🇹 HAÏTI (1-10)
    "1": {
        titre: "Bouki, Malice et le Grand Festin",
        origine: "🇭🇹 Haïti — Tradition orale créole",
        morale: "La ruse peut battre la force, mais la gloutonnerie finit toujours par perdre le gourmand.",
        corps: `
 <p class="tale-opening">Krik ? … Krak ! Tout le monde est là ? Alors écoutez bien !</p> <p class="tale-drop-cap">Il était une fois, dans un village perché sur une colline verte d'Haïti, deux amis très différents : Bouki le costaud et Malice le malin. Bouki avait des épaules larges comme deux buffles et un ventre toujours creux. Malice, lui, était mince comme une liane de bambou, mais son cerveau tournait plus vite qu'une roue de charrette.</p> <p>Un beau matin, le roi du village fit annoncer par son crieur : <span class="dialogue">« Qui remplira ma grange de maïs d'ici demain soir sera invité au grand festin royal ! Il y aura du riz djon-djon, du poulet aux chadèques, des akras croustillants et du rhum clairin ! »</span></p> <p>Bouki entendit le mot "festin" et ses yeux brillèrent comme deux étoiles. Il se mit aussitôt à courir vers le champ. Mais après dix minutes, il était déjà épuisé, allongé sous un manguier, la bouche grande ouverte comme une grotte.</p> <p><span class="dialogue">— Malice, mon ami, dit-il d'une voix douce comme du sirop, tu es si intelligent... aide-moi à remplir cette grange, et je partagerai le festin avec toi !</span></p> <p>Malice sourit de son sourire en coin. Il avait déjà une idée. <span class="dialogue">— D'accord, Bouki. Mais c'est toi qui porteras les sacs ! Moi, je m'occupe du reste.</span></p> <p>Malice courut au village et dit à chaque paysan : <span class="dialogue">« Le roi offre deux pièces d'or à quiconque apporte un sac de maïs à sa grange ce soir ! »</span> Ce n'était pas tout à fait vrai, mais les paysans, alléchés, arrivèrent en masse avec leurs sacs.</p> <p>Pendant ce temps, Bouki portait, portait, portait... jusqu'à ce que la grange déborde de maïs doré.</p> <p>Le soir du festin, ils arrivèrent tous les deux au palais. Les tables pliaient sous les plats fumants. Bouki ne pouvait plus s'arrêter de manger. Il mangeait pour deux, pour quatre, pour huit ! Il mangea tant et tant qu'il ne pouvait plus se lever de sa chaise.</p> <p>Malice, lui, mangea sagement, salua le roi, et rentra chez lui en sifflotant, les mains dans les poches.</p> <p>Bouki, lui, resta coincé dans sa chaise jusqu'au lendemain matin. Et lorsqu'il se réveilla, les serviteurs avaient déjà tout mangé.</p> <p class="tale-closing">Ainsi se termine le conte. Celui qui mange pour demain, finit toujours par dormir aujourd'hui. <br>— Bonjour !</p> `
    },
    "2": {
        titre: "La Rivière qui Chantait",
        origine: "🇭🇹 Haïti — Tradition des montagnes",
        morale: "La nature est vivante. Celui qui la respecte reçoit ses dons ; celui qui la blesse sera blessé à son tour.",
        corps: `<p class="tale-opening">Krik ? Krak ! Alors, ouvrez vos oreilles comme des fleurs au soleil !</p> <p class="tale-drop-cap">Dans les mornes d'Haïti, là où les nuages s'accrochent aux arbres le matin, coulait une rivière pas comme les autres. Elle chantait. Pas comme les oiseaux, pas comme le vent — elle chantait des mots, des vraies chansons en créole, douces comme la voix d'une grand-mère.</p> <p>Les gens du village venaient y puiser de l'eau et, en échange, ils laissaient une petite fleur sur la rive. C'était la coutume. La rivière chantait plus fort quand elle était heureuse.</p> <p>Un jour, arriva dans le village un jeune homme nommé Dieudieu, qui avait grandi en ville et ne connaissait pas les usages. <span class="dialogue">— Pourquoi laisser des fleurs pour de l'eau ? dit-il en riant. L'eau ne voit pas, l'eau n'entend pas !</span></p> <p>Il prit toute l'eau qu'il voulut, sans laisser de fleur. Puis, pour faire le malin, il jeta ses épluchures dans la rivière.</p> <p>La rivière se tut.</p> <p>Le lendemain, quand les villageois vinrent chercher de l'eau, la rivière était asséchée. Plus une goutte. Le chant avait disparu. Les enfants pleuraient, les jardins se fanaient, les animaux avaient soif.</p> <p>Une vieille femme nommée Tante Rosalie prit Dieudieu par la main et l'amena au bord du lit sec. <span class="dialogue">— Tu vois ce que tu as fait ? Maintenant tu vas réparer.</span></p> <p>Dieudieu, honteux, passa trois jours à nettoyer la rive, à replanter des fleurs sauvages, à retirer ses ordures. Le troisième soir, il posa son front sur la terre humide et dit : <span class="dialogue">— Pardonne-moi. Je ne savais pas que tu étais vivante.</span></p> <p>Un petit murmure se fit entendre. Puis un filet d'eau apparut. Puis un flot. Puis la rivière se remit à chanter — cette fois, une chanson nouvelle, plus belle encore, qui disait le pardon et la réconciliation.</p> <p>Dieudieu posa sa première fleur sur la rive et sourit.</p> <p class="tale-closing">— Qui a des oreilles, qu'il entende la rivière. Elle parle encore, si l'on sait écouter.</p>`
    },
    "3": {
        titre: "Ti Jean et le Zombie du Carrefour",
        origine: "🇭🇹 Haïti — Tradition de nuit",
        morale: "Le vrai courage n'est pas l'absence de peur — c'est d'avancer malgré la peur, avec un cœur droit.",
        corps:  `<p class="tale-opening">Krik ? Krak ! Restez bien assis — cette histoire se passe la nuit !</p> <p class="tale-drop-cap">Ti Jean était le plus petit garçon du village. Ses frères aînés, Grandmès et Secondé, étaient grands, forts et très bruyants. Mais Ti Jean, lui, était petit, calme, et observait tout avec ses grands yeux noirs.</p> <p>Un soir, un messager arriva en courant : <span class="dialogue">— Le zombie du carrefour a volé la cloche de l'église ! Sans cette cloche, nos morts ne peuvent pas trouver leur chemin vers le pays des ancêtres !</span></p> <p>Grandmès prit sa machette et se mit en route. Mais quand il vit la brume rouge au carrefour et entendit les chaînes qui tintaient dans le noir, il fit demi-tour en courant si vite que ses sandales restèrent sur place.</p> <p>Secondé prit son bâton et se mit en route. Mais quand une voix profonde comme un puits dit <span class="dialogue">« Qui ose s'approcher ? »</span>, il tomba sur ses genoux et rentra les yeux fermés en récitant des prières.</p> <p>Ti Jean, lui, attendit le milieu de la nuit. Il ramassa trois choses : un morceau de pain de sa maman, un collier de graines de bois d'Inde que lui avait donné sa grand-mère, et une petite lanterne.</p> <p>Au carrefour, la brume était épaisse comme une soupe de giraumon. Une forme grise se dressa devant lui. <span class="dialogue">— Va-t'en, petit, dit la voix. Je mange les enfants curieux.</span></p> <p>Ti Jean ne courut pas. Il s'assit sur une pierre et dit : <span class="dialogue">— Je suis venu te parler, pas te combattre. Tu as pris notre cloche. Pourquoi ?</span></p> <p>Un long silence. Puis le zombie, surpris qu'on lui parle ainsi, murmura : <span class="dialogue">— Parce que personne ne laisse plus d'offrandes pour moi. J'ai été oublié.</span></p> <p>Ti Jean déposa son pain sur la terre. <span class="dialogue">— Tiens. Et maintenant, dis-moi ton nom, pour que je puisse dire aux anciens de te rappeler dans leurs prières.</span></p> <p>Le zombie dit son nom. La brume se dissipa. La cloche apparut dans l'herbe, brillante comme si elle n'était jamais partie.</p> <p>Ti Jean rentra au village avec la cloche sous le bras, et depuis ce jour, on dit que les petits peuvent aller là où les grands ont peur d'aller — pourvu qu'ils aient le cœur droit.</p> <p class="tale-closing">— Bonne nuit, et n'oubliez pas les noms des anciens !</p>`
    },
    "4": {
        titre: "La Tortue et le Secret du Ciel",
        origine: "🇭🇹 Haïti — Conte animalier créole",
        morale: "L'humilité est une force. Vouloir tout avoir par orgueil finit toujours par tout briser.",
        corps: `<p class="tale-opening">Krik ? Krak ! Voici l'histoire de la carapace de la tortue — et pourquoi elle est fêlée !</p> <p class="tale-drop-cap">Autrefois, la tortue avait une carapace lisse et brillante comme un miroir d'eau calme. Elle était si belle que même le soleil s'y regardait en passant.</p> <p>Un soir, les oiseaux du ciel organisèrent un grand festin là-haut dans les nuages. Ils envoyèrent des invitations à tous les animaux du ciel. La tortue, elle, n'avait pas été invitée — car elle ne pouvait pas voler.</p> <p><span class="dialogue">— Cela n'est pas juste ! dit-elle. Je veux y aller !</span></p> <p>La tortue alla voir Malice l'oiseau-menteur. <span class="dialogue">— Prête-moi une plume de chaque oiseau, et je pourrai voler jusqu'au festin !</span></p> <p>Chaque oiseau lui donna une plume. La tortue les attacha à ses bras et monta dans le ciel en battant des membres comme une chose folle. Miracle ! Elle s'éleva ! Elle vola ! Les oiseaux, stupéfaits, la regardèrent arriver.</p> <p>Au festin, la tortue mangea plus que tous les autres réunis. Elle prit les meilleurs morceaux, les posa sous sa carapace et dit : <span class="dialogue">— Tout ce qui est sous ma carapace m'appartient !</span></p> <p>Les oiseaux, furieux, reprirent chacun leur plume.</p> <p>La tortue se retrouva dans le ciel, sans plumes, sans ailes. Elle tomba. Elle tomba longtemps. Elle tomba fort.</p> <p>Quand elle toucha la terre, sa carapace si belle se fêla en mille morceaux. Les fourmis, apitoyées, la recollèrent avec de la boue — c'est pour ça qu'on voit encore aujourd'hui les lignes sur la carapace des tortues.</p> <p>Et depuis ce jour, la tortue marche lentement, la tête basse, et ne lève plus les yeux vers le ciel.</p> <p class="tale-closing">— Qui veut tout avoir perd tout. Prends soin de ce que tu as déjà !</p>`
    },
    "5": {
        titre: "Marinette et les Fleurs de Minuit",
        origine: "🇭🇹 Haïti — Conte des fleurs et esprits",
        morale: "Donner sans compter, même quand on a peu, ouvre des portes que l'on croyait fermées.",
        corps: `<p class="tale-opening">Krik ? Krak ! Préparez vos cœurs — cette histoire est douce comme le miel de canne !</p> <p class="tale-drop-cap">Marinette vivait avec sa vieille mère malade dans une case au bord de la forêt. Elles n'avaient presque rien : quelques patates douces dans la terre, une poule qui pondait un œuf par semaine, et beaucoup d'amour.</p> <p>Un soir de pleine lune, Marinette entendit pleurer dans les buissons. Elle s'approcha et trouva une petite femme toute vêtue de blanc, les pieds nus et les joues mouillées. <span class="dialogue">— Qui êtes-vous ? demanda Marinette. Pourquoi pleurez-vous ?</span></p> <p><span class="dialogue">— Je suis Ezili, dit la femme, et j'ai faim. Mais les gens du village ont peur de moi et ferment leurs portes.</span></p> <p>Marinette n'avait pas grand chose, mais elle n'hésita pas. Elle rentra chez elle, prit son dernier morceau de pain, son unique orange et une tasse de tisane chaude, et les apporta à l'étrangère.</p> <p>Ezili mangea en silence. Puis elle sourit — et quand elle sourit, des étoiles semblèrent tomber dans ses yeux.</p> <p><span class="dialogue">— Tu m'as donné sans rien attendre. Je vais te donner à mon tour.</span></p> <p>Elle souffla dans ses mains. Des graines minuscules en tombèrent. <span class="dialogue">— Plante-les sous la fenêtre de ta mère, ce soir même, et arrose-les de l'eau de rosée du matin.</span></p> <p>Marinette fit ce qu'on lui avait dit. À minuit, des fleurs d'un violet profond sortirent de terre, brillant comme des lanternes. Leur parfum entra par la fenêtre et emplit la case d'une douce chaleur.</p> <p>Le lendemain matin, la mère de Marinette se leva pour la première fois depuis des mois. Ses yeux étaient clairs, ses joues roses. <span class="dialogue">— J'ai rêvé que des fleurs chantaient pour moi toute la nuit, dit-elle en souriant.</span></p> <p>Marinette regarda ses fleurs, puis le ciel, et dit merci à voix basse — sans savoir tout à fait à qui.</p> <p class="tale-closing">— La générosité, c'est la clé du ciel. Même la plus petite clé peut ouvrir la plus grande porte.</p>`
    },
    "6": {
        titre: "Bouki et le Puits Magique",
        origine: "🇭🇹 Haïti — Aventures de Bouki",
        morale: "La paresse est une dette que l'on paie toujours deux fois. Le vrai puits magique est le travail.",
        corps: `<p class="tale-opening">Krik ? Krak ! Cette histoire-là, mes enfants, fait rire et réfléchir à la fois !</p> <p class="tale-drop-cap">Bouki n'aimait rien autant que dormir à l'ombre. Un jour, Malice s'approcha de lui avec un grand sourire. <span class="dialogue">— Bouki, mon cher ami, as-tu entendu la nouvelle ? Il existe un puits magique dans la forêt. Quiconque y jette une graine de maïs reçoit cent sacs de maïs le lendemain !</span></p> <p><span class="dialogue">— Vraiment ?</span> dit Bouki, les yeux grands ouverts.</p> <p><span class="dialogue">— Vraiment. Mais il faut travailler dur toute une journée pour y arriver.</span></p> <p>Bouki, qui n'avait jamais travaillé dur de sa vie, décida quand même d'y aller — car cent sacs de maïs valaient bien un effort. Il marcha sous le soleil brûlant, traversa trois collines, deux ravines et une forêt d'épineux.</p> <p>Finalement, il arriva devant un vieux puits de pierre moussu. Il jeta sa graine de maïs dedans. Il entendit un plouf.</p> <p>Et rien d'autre.</p> <p>Il attendit. Une heure. Deux heures. Sous un soleil de plomb. Puis il cria dans le puits : <span class="dialogue">— Holà ! Mes cent sacs de maïs ?!</span></p> <p>Une grenouille sauta hors du puits et atterrit sur le nez de Bouki.</p> <p>Bouki rentra chez lui épuisé, avec rien de plus qu'une grenouille. En chemin, il croisa Malice qui se tenait les côtes de rire derrière un arbre.</p> <p><span class="dialogue">— Le vrai puits magique, dit Malice entre deux éclats de rire, c'est la terre ! Jette une graine, arrose-la, travaille, et dans quelques mois tu auras tes cent sacs. Mais ça, Bouki, ça s'appelle du travail !</span></p> <p>Bouki regarda la grenouille dans sa main. La grenouille le regarda aussi, d'un air qui semblait dire : <em>il avait raison, tu sais.</em></p> <p class="tale-closing">— La magie la plus puissante du monde, c'est le travail. Demande aux paysans — ils le savent depuis toujours.</p>`
    },
    "7": {
        titre: "La Fille des Étoiles",
        origine: "🇭🇹 Haïti — Conte céleste",
        morale: "Les anciens nous donnent des règles pour nous protéger, respectez leur sagesse.",
        corps: `<p class="tale-opening">Krik ? Krak ! Regardez le ciel — chaque étoile a son histoire !</p> <p class="tale-drop-cap">Il était une fois une petite fille nommée Céleste qui aimait plus que tout regarder le ciel la nuit. Elle connaissait toutes les étoiles par leur nom et leur chantait des berceuses créoles.</p> <p>Un soir, une étoile filante tomba tout près d'elle dans le jardin, laissant une lueur dorée dans l'herbe. Céleste s'approcha et trouva une petite lumière qui battait comme un cœur. Sa grand-mère l'appela depuis la case :</p> <p><span class="dialogue">— Céleste ! Si tu trouves une lumière dans le jardin, ne la touche pas ! Les étoiles tombées appartiennent aux lwa — les esprits du ciel !</span></p> <p>Céleste hésita. La lumière était si belle ! Elle tendit la main... et la retira. Elle pensa à sa grand-mère. Elle dit à la lumière : <span class="dialogue">— Je ne peux pas te prendre. Mais je vais rester près de toi cette nuit pour te garder.</span></p> <p>Elle s'assit dans l'herbe et veilla toute la nuit, sans dormir, en chantant doucement.</p> <p>À l'aube, la lumière se souleva doucement et remonta vers le ciel. Et au moment où elle disparaissait, une voix légère comme un souffle dit : <span class="dialogue">— Merci, enfant des hommes. Parce que tu as respecté les règles des anciens, je te donne un don : tu verras toujours juste, même dans le noir.</span></p> <p>Depuis ce jour, Céleste ne se perdit jamais, ni dans les mornes, ni dans la vie. Et chaque soir, une étoile particulière brillait un peu plus fort pour elle — comme pour lui dire bonsoir.</p> <p class="tale-closing">— Écoutez les anciens. Ils voient des choses que nos jeunes yeux ne voient pas encore.</p>`
    },
    "8": {
        titre: "Malice et le Diable aux Pieds Fourchus",
        origine: "🇭🇹 Haïti — Ruse contre mal",
        morale: "L'intelligence et l'esprit vif sont de meilleures armes que les muscles ou la peur.",
        corps: `<p class="tale-opening">Krik ? Krak ! Attention, les enfants — cette histoire chatouille !</p> <p class="tale-drop-cap">Un jour, Malice se retrouva face au Diable lui-même — celui qu'on appelle Bawon dans le pays, avec ses deux pieds fourchus qui faisaient des trous dans la terre à chaque pas. Il portait un chapeau haut-de-forme et une veste noire, et ses yeux brillaient comme des braises.</p> <p><span class="dialogue">— Malice ! dit le Diable. Tu es le seul homme qui ne soit jamais venu me voir. Tous les autres sont venus me demander quelque chose. Pourquoi pas toi ?</span></p> <p><span class="dialogue">— Parce que je n'ai besoin de rien que je ne puisse obtenir par moi-même, dit Malice sans trembler.</span></p> <p>Le Diable ricana. <span class="dialogue">— Vraiment ? Alors jouons. Si tu me bats à trois épreuves, tu pourras rentrer chez toi. Si je gagne, tu m'appartiens.</span></p> <p>Première épreuve : qui courrait le plus vite ? Malice dit : <span class="dialogue">— Je cours si vite que ma propre ombre ne me rattrape pas. Mais aujourd'hui, j'ai un rhume au pied. Laisse-moi envoyer mon petit frère à ma place.</span> Il alla chercher un lièvre dans les buissons et le présenta. Le lièvre fila comme l'éclair. Le Diable perdit.</p> <p>Deuxième épreuve : qui soulèverait le plus lourd rocher ? Malice dit : <span class="dialogue">— Je soulève des montagnes d'habitude. Mais aujourd'hui, je ne veux pas abîmer les pierres des environs. Soulève toi-même ce rocher, et je ferai pareil avec le suivant.</span> Le Diable souleva le rocher. Malice chercha longtemps le "suivant" et dit finalement : <span class="dialogue">— Je ne vois aucun rocher assez digne de mes bras. Tu gagnes cette manche.</span></p> <p>Troisième épreuve : qui ferait peur à l'autre ? Le Diable rugit, cracha du feu, fit trembler la terre. Malice bâilla et dit : <span class="dialogue">— Mon oncle ronfle plus fort que ça. À mon tour.</span> Il s'approcha du Diable et lui chuchota quelque chose à l'oreille.</p> <p>On ne sut jamais ce que Malice lui avait dit. Mais le Diable devint blanc comme de la chaux, fit ses deux pieds fourchus et disparut dans un nuage de soufre.</p> <p>Malice rentra chez lui en sifflotant.</p> <p class="tale-closing">— Contre la peur, la meilleure arme, c'est la tête. Gardez-la bien droite sur vos épaules !</p>`
    },
    "9": {
        titre: "Le Mapou et l'Enfant Solitaire",
        origine: "🇭🇹 Haïti — Conte de l'arbre sacré",
        morale: "L'amitié véritable ne demande ni richesse ni beauté — elle demande seulement un cœur ouvert.",
        corps: `<p class="tale-opening">Krik ? Krak ! Voici l'histoire d'un arbre qui avait un cœur plus grand que ses racines !</p> <p class="tale-drop-cap">Au centre du village se dressait un grand mapou, l'arbre sacré des lwa. Ses racines sortaient de terre comme des bras géants, et son ombre couvrait la moitié de la place. Les gens disaient qu'il était là depuis si longtemps qu'il avait vu naître les grands-parents des grands-parents.</p> <p>Personne ne jouait sous le mapou. Les adultes disaient que les esprits y habitaient, et les enfants avaient peur.</p> <p>Sauf un garçon nommé Jesnel. Jesnel était différent des autres enfants : il avait une jambe un peu tordue et boitait en marchant. Les autres enfants ne jouaient pas avec lui. Alors il venait s'asseoir seul contre les racines du mapou.</p> <p>Un après-midi, il entendit une voix profonde et douce comme du tambour de bambou : <span class="dialogue">— Pourquoi es-tu triste, petit ?</span></p> <p>Jesnel sursauta et regarda autour de lui. Personne. <span class="dialogue">— C'est toi, le mapou ? dit-il.</span></p> <p><span class="dialogue">— Oui. Je regarde les gens depuis des siècles. Je sais reconnaître la solitude.</span></p> <p>Et ainsi commença une drôle d'amitié. Le mapou raconta à Jesnel l'histoire du village, des guerres et des fêtes d'antan. Jesnel, en échange, lui racontait ce qui se passait chaque jour — les potins, les rires, les pleurs.</p> <p><span class="dialogue">— Tu vois ces enfants qui ne jouent pas avec toi ? dit un jour le mapou. Dans dix ans, tu auras voyagé, appris et vu des choses que leurs parents n'ont jamais vues. Ce que tu vis seul aujourd'hui te rend fort pour demain.</span></p> <p>Jesnel grandit, devint instituteur, et revint vivre au village. Il enseigna aux enfants l'histoire du mapou, et depuis ce jour, les enfants jouaient de nouveau sous l'arbre — sans peur, avec respect.</p> <p>Et parfois, ceux qui s'asseyaient seuls contre ses racines entendaient une voix douce leur dire : <span class="dialogue">— Je t'écoute.</span></p>`
    },
    "10": {
        titre: "Pourquoi le Crabe n'a Pas de Tête",
        origine: "🇭🇹 Haïti — Conte étiologique créole",
        morale: "L'impatience et la gourmandise peuvent nous faire perdre ce que nous avons de plus précieux.",
        corps: `<p class="tale-opening">Krik ? Krak ! Vous êtes-vous déjà demandé pourquoi le crabe porte ses yeux sur des bâtons ?</p> <p class="tale-drop-cap">Autrefois, le crabe avait une belle tête ronde avec deux grands yeux brillants, perchée fièrement sur son corps. Il était le plus beau de tous les animaux de la mer et de la mangrove — et il le savait.</p> <p>Un jour, la mer organisa un grand festin. Il y aurait des coquillages, des algues sucrées, du corail frit et de la boue parfumée. Tous les animaux de l'eau étaient invités.</p> <p>Le crabe était tellement impatient qu'il arriva deux heures avant tout le monde. La table était dressée mais pas encore servie. <span class="dialogue">— Je vais juste goûter un tout petit peu, dit-il. Personne ne verra.</span></p> <p>Il plongea sa tête dans le grand plat de corail frit. Il mangea. Et mangea. Et mangea tellement que sa tête se coinça dans le plat.</p> <p>Quand les autres animaux arrivèrent, ils trouvèrent le crabe qui courait en tous sens, la tête coincée dans un plat de corail frit, se cognant contre les rochers.</p> <p>La pieuvre, apitoyée, tira le plat. La crevette poussa. Le dauphin tira de l'autre côté. Finalement, le plat se détacha — mais la tête du crabe resta à l'intérieur.</p> <p>On chercha partout la tête du crabe. On la retrouva dans les fonds marins, les yeux grand ouverts, l'air un peu penaud.</p> <p>La mer, bienveillante, posa les deux yeux sur deux petits bâtons et les fixa sur le corps du crabe à la place de sa tête perdue. <span class="dialogue">— Tu n'as plus de tête, dit-elle, mais tu pourras quand même voir dans toutes les directions. Peut-être que cela t'apprendra à regarder avant de plonger.</span></p> <p>Depuis ce jour, le crabe a les yeux perchés sur des petits bâtons, marche de côté — parce qu'il ne sait plus trop où est l'avant — et n'a toujours pas retrouvé sa tête.</p> <p class="tale-closing">— Patience, mes enfants. La gourmandise, ça coûte cher — même une tête !</p>`
    },

    // 🌍 AFRIQUE (11-25)
    "11": {
        titre: "Anansi et la Boîte à Histoires",
        origine: "🌍 Ghana — Tradition Akan/Ashanti",
        morale: "La connaissance et les histoires sont les plus grands trésors, elles appartiennent à tous.",
        corps: `<p class="tale-opening">Au commencement, les histoires n'existaient pas sur Terre. Elles étaient toutes enfermées dans une boîte d'or chez Nyame, le Dieu du Ciel...</p> <p class="tale-drop-cap">Anansi l'araignée était petit, à huit pattes, et vivait dans un recoin d'une grande forêt de l'Ashanti. Mais son esprit était aussi vaste que le ciel de la savane. Un jour, il décida de monter chez Nyame pour lui acheter sa boîte à histoires.</p> <p>Nyame, installé sur son nuage d'or, rit quand il vit l'araignée. <span class="dialogue">— Cette boîte ? Des rois et des guerriers l'ont demandée. Qu'est-ce qu'une petite araignée peut m'offrir en échange ?</span></p> <p><span class="dialogue">— Ce que vous voulez, dit Anansi. Dites votre prix.</span></p> <p>Nyame, pour s'amuser, dit : <span class="dialogue">— Capture le Nyan Kopon, le frelon géant qui n'a jamais été attrapé. Capture Onini, le python qui avale les éléphants. Et capture Osebo, le léopard aux dents d'ivoire.</span></p> <p>Les gens du village entendirent et secouèrent la tête. Impossible. Mais Anansi sourit.</p> <p>Pour le frelon, il prit une calebasse et fit semblant de se protéger de la pluie en dessous. Il cria : <span class="dialogue">— Malheureux frelon ! La pluie va te tremper les ailes ! Entre donc dans cette calebasse !</span> Le frelon curieux entra. Anansi ferma la calebasse.</p> <p>Pour le python, il coupa une branche et dit en passant près de lui : <span class="dialogue">— Mon ami python, je parie que tu es moins long que cette branche.</span> Le python, vexé, se coucha à côté de la branche pour comparer. Anansi l'attacha rapidement avec sa soie d'araignée.</p> <p>Pour le léopard, il creusa un trou et le couvrit de feuilles. Le léopard tomba dedans, et Anansi l'enferma dans un filet.</p> <p>Quand Anansi remonta au ciel avec ses trois prisonniers, Nyame fut si impressionné qu'il ouvrit la boîte et en déversa le contenu sur la Terre. Les histoires se répandirent dans l'air, dans le vent, dans les bouches des conteurs.</p> <p>Et c'est pour cela qu'on appelle encore aujourd'hui les histoires "des contes d'Anansi" — parce que c'est lui qui nous les a apportées.</p>`
    },
    "12": {
        titre: "Le Lion qui Avait Peur du Moustique",
        origine: "🌍 Afrique de l'Ouest — Conte des savanes",
        morale: "L'orgueil cache souvent une faiblesse. Personne n'est invincible, même le plus fort.",
        corps: `<p class="tale-opening">Sous l'acacia de la grande savane, les animaux se rassemblèrent un jour pour juger une dispute extraordinaire...</p> <p class="tale-drop-cap">Le lion Koffi était le roi de la savane. Chaque animal tremblait à son rugissement. Son crin doré brillait sous le soleil, et il se promenait toujours en disant : <span class="dialogue">— Je suis le plus fort. Je n'ai peur de rien ni de personne !</span></p> <p>Un soir, un tout petit moustique vint se poser sur l'oreille du lion et dit d'une voix minuscule : <span class="dialogue">— Roi des animaux, je te défie.</span></p> <p>Les animaux qui regardaient de loin éclatèrent de rire. Le lion rugit si fort que les oiseaux quittèrent les arbres. <span class="dialogue">— Un moustique me défie ?! Part avant que je te mange !</span></p> <p><span class="dialogue">— Je dis simplement que je peux te faire fuir, dit le moustique.</span></p> <p>Le lion rugit encore. Le moustique attendit. Puis, très calmement, il piqua le lion sur l'intérieur de l'oreille — là où le poing le plus fort ne peut pas atteindre. Une, deux, dix fois.</p> <p>Le lion se roula par terre. Il se gratta l'oreille avec sa grosse patte, mais le moustique virevoltait, disparaissait, revenait. Le lion hurla, courut, se jeta dans la rivière — rien n'y fit.</p> <p>Finalement, épuisé, le lion se coucha et dit d'une toute petite voix : <span class="dialogue">— D'accord, j'ai peur de toi.</span></p> <p>Le moustique se posa sur un brin d'herbe et dit : <span class="dialogue">— Je ne voulais pas te faire de mal, grand roi. Je voulais seulement te rappeler que même le plus petit peut déjouer le plus grand. La prochaine fois que tu diras "je n'ai peur de rien", souviens-toi de moi.</span></p> <p>Et depuis ce jour, on dit que chaque fois qu'un lion rugit dans la nuit, c'est qu'un moustique lui a chatouillé l'oreille.</p>`
    },
    "13": {
        titre: "Sundiata, l'Enfant qui ne Marchait Pas",
        origine: "🌍 Mali — Épopée Mandingue",
        morale: "La persévérance peut tout surmonter. Ce qui semble impossible aujourd'hui est la victoire de demain.",
        corps: `<p class="tale-opening">Voici l'histoire du Lion du Mandé — celui qui naquit faible et devint la plus grande lumière de son peuple...</p> <p class="tale-drop-cap">Dans le grand empire du Mali, un roi avait un fils nommé Sundiata. Mais quand l'enfant eut sept ans, il ne marchait toujours pas. Ses jambes ne le portaient pas. Il se traînait sur le sol comme un lézard, et les autres enfants se moquaient de lui.</p> <p>La mère de Sundiata, Sogolon, souffrait de voir son fils ainsi. Les femmes jalouses du palais disaient : <span class="dialogue">— Ton fils est un serpent sans venin. Il ne sera jamais roi.</span></p> <p>Un soir, Sogolon pleura devant son fils. Sundiata vit les larmes de sa mère. Quelque chose se réveilla en lui — quelque chose de chaud comme de la braise.</p> <p><span class="dialogue">— Mère, ne pleure plus. Demain, je marcherai.</span></p> <p>Le lendemain matin, alors que tout le palais dormait encore, Sundiata demanda qu'on lui apporte la plus grande tige de fer du forgeron. Il la planta dans la terre, posa ses deux mains dessus, et poussa. Ses bras tremblaient. Ses jambes tremblaient. Il poussa encore.</p> <p>Et la tige se courba sous la force de Sundiata — mais l'enfant, lui, se releva.</p> <p>Il était debout. Ses jambes portaient son corps pour la première fois. Ses yeux brillaient comme deux étoiles dans le matin rouge.</p> <p><span class="dialogue">— Mère, dit-il. Je peux marcher.</span></p> <p>Sogolon courut vers lui et le serra contre elle, les joues mouillées mais le cœur débordant de lumière.</p> <p>Les années passèrent. Sundiata grandit fort comme un lion. Il chassa les envahisseurs du Mandé, réunit son peuple, et devint le premier grand roi de l'Empire du Mali. Les griots chantent encore son nom aujourd'hui autour des feux.</p> <p class="tale-closing">— Ce que tu ne peux pas faire aujourd'hui, peut devenir ta plus grande force demain. Ne renonce jamais.</p>`
    },
    "14": {
        titre: "La Fille qui Épousait les Étoiles",
        origine: "🌍 Nigeria — Tradition Yoruba",
        morale: "La sagesse consiste à choisir avec son cœur et sa raison, pas seulement avec les yeux.",
        corps: `<p class="tale-opening">Dans le pays Yoruba, sous les fromagers géants, on raconte cette histoire aux jeunes filles le soir de la pleine lune...</p> <p class="tale-drop-cap">Adaeze était une jeune fille de grande beauté qui vivait au bord du Niger. Chaque nuit, elle regardait le ciel et disait : <span class="dialogue">— Je n'épouserai que la plus belle étoile du ciel. Pas un paysan, pas un guerrier, pas un forgeron — une étoile !</span></p> <p>Ses parents souriaient tristement. Mais Adaeze était têtue comme un buffle.</p> <p>Un soir, une étoile descendit du ciel sous la forme d'un jeune homme d'une beauté éblouissante. Il avait des cheveux comme la nuit, des yeux qui brillaient comme des torches, et il sentait le vent de la haute nuit.</p> <p><span class="dialogue">— Je suis Etoile de l'Est, dit-il. Je t'ai entendue et je suis venu.</span></p> <p>Adaeze accepta de l'épouser immédiatement. Elle quitta sa famille sans se retourner.</p> <p>Mais une fois dans le pays des étoiles, Adaeze découvrit que son mari ne dormait jamais, ne mangeait jamais, ne riait jamais. Il brillait — c'est tout. Il ne pouvait pas s'asseoir avec elle sous un arbre, partager une graine de kola, écouter le son du balafon.</p> <p>Adaeze comprit alors ce qu'elle avait perdu. Elle demanda à rentrer chez elle. L'Étoile de l'Est, qui ne savait pas pleurer, la raccompagna en silence jusqu'au bord de la Terre.</p> <p>Quand Adaeze retrouva sa famille, elle vit son voisin Emeka — le forgeron qu'elle avait refusé — qui jouait avec ses enfants sous le fromager. Il rit en la voyant, sans rancune. Il avait des mains calleuses et un visage ordinaire. Mais il avait un rire vrai.</p> <p>Adaeze s'assit avec eux et apprit, ce jour-là, ce que signifie la chaleur humaine.</p> <p class="tale-closing">— Un cœur qui bat vrai vaut mille éclats de beauté froide. Choisissez avec le cœur !</p>`
    },
    "15": {
        titre: "Pourquoi le Baobab est à l'Envers",
        origine: "🌍 Tanzanie — Tradition Swahili",
        morale: "L'ingratitude et l'orgueil peuvent retourner notre vie comme un arbre déraciné.",
        corps: `<p class="tale-opening">Jambo ! Dans les grandes plaines du Serengeti, chaque baobab raconte une histoire...</p> <p class="tale-drop-cap">Au commencement du monde, quand Mungu créa les arbres, il appela chacun d'eux et leur donna un pays où vivre. L'acacia alla dans la savane, le palmier près de la mer, le manguier près des villages.</p> <p>Puis Mungu appela le Baobab. <span class="dialogue">— Toi, dit Mungu, tu iras dans les plaines arides, où il ne pleut que peu. Tu seras gros, fort, et tes fruits nourriront les animaux et les hommes.</span></p> <p>Le Baobab se regarda. Il était gros, ridé, avec des branches tout emmêlées. <span class="dialogue">— Non, dit-il. Je veux aller près du lac, où il fait frais et où les autres beaux arbres se regardent dans l'eau.</span></p> <p>Mungu lui demanda trois fois. Trois fois le Baobab refusa en se plaignant de son apparence.</p> <p>Finalement, patient mais déçu, Mungu prit le Baobab et le replanta à l'envers — racines vers le ciel, branches dans la terre. <span class="dialogue">— Puisque tu ne veux pas voir les bénédictions que je t'ai données, dit Mungu, tu regarderas le ciel. Peut-être comprendras-tu alors d'où vient ta force.</span></p> <p>Et le Baobab, ainsi planté à l'envers, devint l'arbre le plus utile de la savane. Ses racines touchaient le ciel et semblaient prier. Son tronc immense stockait l'eau des pluies. Ses fruits — les baobabs — nourrissaient les singes, les éléphants, les hommes.</p> <p>On dit qu'il comprit sa leçon — et qu'il est le seul arbre à ne jamais cesser de grandir.</p> <p class="tale-closing">— Soyez reconnaissants pour ce que vous êtes. Vos racines vous nourrissent, même si vous ne les voyez pas.</p>`
    },
    "16": {
        titre: "Le Lièvre et la Pluie de Miel",
        origine: "🌍 Éthiopie — Tradition Oromo",
        morale: "Le plus faible peut déjouer le plus fort en utilisant son intelligence plutôt que ses muscles.",
        corps: `<p class="tale-opening">Sous les acajous d'Éthiopie, les mères racontent cette histoire à leurs enfants pour les faire rire et réfléchir en même temps...</p> <p class="tale-drop-cap">Dans les hautes terres d'Éthiopie, un lièvre nommé Dinku vivait entre les rochers rouges et les buissons d'épineux. Il était maigre, rapide et toujours affamé. Un éléphant nommé Gobena régnait sur la forêt et prenait toujours la meilleure part de tout — les meilleurs fruits, les meilleures herbes, la meilleure eau.</p> <p>Un matin, Dinku trouva une ruche sauvage pleine d'un miel ambré et parfumé. Avant qu'il ait pu en prendre, l'éléphant arriva en soufflant et mangea tout le miel en trois coups de langue.</p> <p><span class="dialogue">— C'est ma forêt, dit Gobena. Tout ce qui est dans ma forêt m'appartient.</span></p> <p>Dinku réfléchit trois jours. Puis il alla voir l'éléphant avec un grand sourire. <span class="dialogue">— Grand Gobena, dit-il, j'ai découvert quelque chose d'extraordinaire ! Dans le ravin à l'est, une source de miel jaillit du rocher. Il y en a pour des années !</span></p> <p>L'éléphant courut vers le ravin. Dinku, qui connaissait les lieux, lui avait décrit un endroit escarpé, plein de boue et de guêpes sauvages.</p> <p>L'éléphant tomba dans la boue, se fit piquer par les guêpes, et mit deux jours à se sortir du ravin.</p> <p>Pendant ce temps, Dinku mangea tout le miel qu'il trouva, en laissa une part pour ses voisins, et offrit même quelques morceaux de rayon à une famille de singes.</p> <p>Quand Gobena revint, couvert de boue et de piqûres, Dinku lui dit gentiment : <span class="dialogue">— Peut-être que si tu partageais, les autres t'aideraient à trouver le vrai miel.</span></p> <p>L'éléphant, humilié, réfléchit. Et pour la première fois, il partagea.</p> <p class="tale-closing">— Une forêt partagée nourrit mieux qu'une forêt gardée. Dinku l'avait bien compris !</p> `
    },
    "17": {
        titre: "Oya et le Vent du Changement",
        origine: "🌍 Nigeria — Panthéon Yoruba",
        morale: "Le changement fait peur, mais il est le chemin vers quelque chose de plus grand.",
        corps: `<p class="tale-opening">Dans le pays Yoruba, Oya est l'Orisha des tempêtes et du changement. Voici comment elle apprit aux hommes à ne pas avoir peur...</p> <p class="tale-drop-cap">Il était une fois un village au bord du Niger dont les habitants avaient très peur du vent. Chaque fois qu'une brise se levait, ils fermaient leurs volets, se cachaient sous leurs lits et priaient pour que ça s'arrête. Ils avaient peur que le vent emporte leurs maisons, leurs récoltes, leur vie.</p> <p>La déesse Oya les observait depuis son palais de nuages violets, son éventail d'ailes de paon à la main. Elle soupira.</p> <p>Une nuit, elle descendit sous la forme d'une vieille femme couverte de pagnes rouge et noir. Elle s'installa au coin du marché et attendit.</p> <p>Une petite fille nommée Folake s'approcha. <span class="dialogue">— Vieille femme, pourquoi souris-tu quand le vent souffle et que tout le monde a peur ?</span></p> <p><span class="dialogue">— Parce que le vent est mon ami, dit Oya. Il emporte les vieilles choses pour faire place aux nouvelles.</span></p> <p><span class="dialogue">— Mais il emporte aussi ce qu'on aime !</span> dit Folake.</p> <p><span class="dialogue">— Oui. Parfois. Mais regarde : quand le vent emporte les vieilles feuilles, de nouvelles feuilles poussent. Quand le vent emporte les nuages noirs, le soleil revient. Le vent ne détruit pas, il transforme.</span></p> <p>Cette nuit-là, la tempête la plus violente de l'année frappa le village. Mais Folake ne se cacha pas. Elle sortit dans la cour, les bras ouverts, et laissa le vent la traverser.</p> <p>Quand la tempête se calma, le vieux grenier vermoulu s'était effondré — mais à sa place, les fondations parfaites pour en construire un nouveau, plus solide, plus grand.</p> <p><span class="dialogue">— Le vent savait, dit Folake. Il savait que le vieux grenier allait tomber. Il nous a aidés à le laisser partir.</span></p> <p class="tale-closing">— Le changement fait peur. Mais Oya veille. Elle ne détruit que ce qui doit partir pour que quelque chose de plus beau puisse venir.</p>`
    },
    "18": {
        titre: "La Hyène et la Lune Volée",
        origine: "🌍 Sénégal — Tradition Wolof",
        morale: "Le mensonge a des jambes courtes. La vérité finit toujours par revenir éclairer le monde.",
        corps: `<p class="tale-opening">Au Sénégal, sous le neem et le fromager, les conteurs commencent toujours ainsi : « Il était une vérité... »</p> <p class="tale-drop-cap">Une nuit, la lune disparut. Pas à cause des nuages — elle disparut vraiment. Le ciel était noir, les animaux se cognaientles uns aux autres, les enfants pleuraient, les paysans ne pouvaient plus trouver leur chemin.</p> <p>Le conseil des animaux se réunit d'urgence. <span class="dialogue">— Quelqu'un a vu quelque chose ? demanda le vieux lion.</span></p> <p>La hyène Bouki-daga s'avança, les yeux brillants d'un air faussement innocent. <span class="dialogue">— Je n'ai rien vu, dit-elle. Mais j'ai entendu dire que c'est le hibou qui l'a prise — il vole la nuit, et personne ne le voit !</span></p> <p>Le hibou, scandalise, protestait. Mais qui croirait le hibou aux yeux ronds contre la parole d'une hyène si sûre d'elle ?</p> <p>Heureusement, une tortue âgée nommée Ndéye avait tout vu. Elle avait vu la hyène glisser la lune sous son manteau et la cacher dans une termitière creuse.</p> <p>Ndéye ne dit rien tout de suite. Elle alla voir la hyène seule à seule. <span class="dialogue">— Bouki-daga, dit-elle doucement, je sais. Et toi, tu sais que je sais. La question n'est pas si la vérité sera connue — elle le sera toujours. La question est : veux-tu la dire toi-même, ou attendre qu'on la découvre ?</span></p> <p>La hyène regarda la vieille tortue longtemps. Puis, les épaules basses, elle alla chercher la lune dans la termitière et la déposa dans l'herbe.</p> <p>La lune remonta lentement dans le ciel, plus brillante que jamais — comme si elle avait profité de son voyage pour se reposer.</p> <p>La hyène dit simplement : <span class="dialogue">— Je voulais avoir un peu de cette lumière pour moi. Je ne savais pas que vous en aviez tous besoin.</span></p> <p>Le vieux lion dit : <span class="dialogue">— Il y a assez de lumière pour tous, Bouki-daga. Tu n'avais qu'à demander.</span></p> <p class="tale-closing">— La vérité est comme la lune : on peut la cacher un moment, mais elle revient toujours éclairer le ciel.</p>`
    },
    "19": {
        titre: "Kofi et le Tambour du Ciel",
        origine: "🌍 Ghana — Tradition Akan",
        morale: "La créativité et le travail transforment les dons ordinaires en miracles.",
        corps: `<p class="tale-opening">Akwaaba ! Bienvenue dans l'histoire du garçon qui fit danser même les étoiles...</p> <p class="tale-drop-cap">Kofi était le fils d'un forgeron de l'Ashanti. Ses frères savaient manier le fer, forger des couteaux et des bracelets. Kofi, lui, n'avait qu'une chose : un talent pour le rythme. Il tapait sur tout — les marmites, les troncs d'arbres, les calebasses séchées — et en faisait de la musique.</p> <p><span class="dialogue">— Ce n'est pas un métier, disait son père. Apprends à forger comme tes frères.</span></p> <p>Mais les mains de Kofi semblaient faites pour les tambours, pas pour le métal.</p> <p>Un jour, le roi de l'Ashanti annonça un grand concours : celui qui créerait un son capable de faire pleuvoir serait récompensé — car la sécheresse durait depuis des mois et les enfants avaient soif.</p> <p>Ses frères forgèrent de beaux instruments de métal poli. Les griots vinrent avec leurs djembés. Les sorciers soufflèrent dans leurs cornes.</p> <p>Rien. Le ciel restait de pierre.</p> <p>Kofi, lui, passa trois jours et trois nuits à fabriquer un tambour avec des matériaux simples : la peau d'un cabri, du bois de neem, des cordes tressées par sa mère. Il écouta le vent, le ruisseau, le battement de son propre cœur.</p> <p>Quand il joua, ce fut d'abord tout doucement — un murmure de rythme. Puis plus fort, comme la marche des éléphants sur la savane sèche. Puis comme le tonnerre lointain qui s'approche.</p> <p>Et le ciel s'ouvrit. La pluie tomba.</p> <p>Les gens dansèrent sous la pluie en criant le nom de Kofi. Son père s'approcha, les yeux humides, et posa la main sur l'épaule de son fils. <span class="dialogue">— Pardonne-moi, dit-il. Je ne savais pas que les tambours pouvaient forger la pluie.</span></p> <p class="tale-closing">— Chaque don est précieux. Ne laissez personne vous dire que le vôtre ne compte pas.</p>`
    },
    "20": {
        titre: "Le Serpent Arc-en-Ciel et la Pluie",
        origine: "🌍 Zimbabwe — Tradition Shona",
        morale: "Le partage crée l'abondance. Ce que l'on donne revient toujours multiplié.",
        corps: `<p class="tale-opening">Dans le pays Shona du Zimbabwe, on dit que l'arc-en-ciel est le dos du grand serpent Nyami Nyami qui dort dans le fleuve Zambèze...</p> <p class="tale-drop-cap">Il y avait deux villages de part et d'autre d'une rivière. Le village du nord avait beaucoup de pluie — ses jardins débordaient de légumes, ses greniers croulaient sous le maïs et le millet. Le village du sud était sec — ses enfants avaient faim, ses terres craquelaient comme des vieilles poteries.</p> <p>Les gens du village du nord fermaient leurs greniers à clef. <span class="dialogue">— Nous avons travaillé. Pourquoi partagerions-nous ?</span></p> <p>Un soir, un enfant du village du nord, nommé Tariro, traversa la rivière pour jouer avec des amis du village du sud. Il vit les enfants qui n'avaient pas mangé. Il rentra chez lui en pleurant.</p> <p>Cette nuit-là, il sortit en secret avec un grand sac de maïs et alla le déposer devant les portes du village du sud. Mais en chemin, il s'arrêta sur le pont et vit une lumière dans l'eau.</p> <p>C'était Nyami Nyami, le grand serpent arc-en-ciel, dont les écailles brillaient de toutes les couleurs. <span class="dialogue">— Petit, dit le serpent d'une voix comme le courant d'eau, tu as bon cœur. Que veux-tu en échange ?</span></p> <p><span class="dialogue">— Rien, dit Tariro. Je veux juste que les enfants mangent.</span></p> <p>Nyami Nyami sourit de son sourire de serpent. Le lendemain, la pluie tomba également sur les deux villages. Les greniers du village du nord se remplirent encore plus qu'avant — comme si donner avait fait de la place pour recevoir davantage.</p> <p>Et l'on dit que depuis ce jour, chaque fois qu'on voit un arc-en-ciel au Zimbabwe, c'est Nyami Nyami qui rappelle aux gens que les rivières n'appartiennent à personne — et que l'eau, comme l'amour, se partage.</p> <p class="tale-closing">— Donner, c'est agrandir son propre grenier. Nyami Nyami vous le dit !</p>`
    },
    "21": {
        titre: "Pourquoi les Éléphants ont une Bonne Mémoire",
        origine: "🌍 Kenya — Tradition Kikuyu",
        morale: "Se souvenir de ceux qui nous ont aidés est la plus belle forme de gratitude.",
        corps: `<p class="tale-opening">Karibu ! Dans les savanes du Kenya, les Kikuyu disent que les éléphants pleurent pour les mêmes raisons que les hommes...</p> <p class="tale-drop-cap">Autrefois, les éléphants oubliaient tout. Comme les autres animaux, ils ne se souvenaient pas d'un jour à l'autre, d'une saison à l'autre. C'est une vieille femme Kikuyu nommée Nyambura qui leur offrit la mémoire.</p> <p>Nyambura vivait seule depuis que ses enfants étaient partis en ville. Elle soignait un jeune éléphant qui avait perdu sa mère dans les herbes hautes. Elle l'appela Ndovu et lui donna à manger chaque jour pendant une saison entière.</p> <p>Quand Ndovu fut assez fort pour rejoindre le troupeau, il s'en alla sans se retourner — comme font tous les animaux qui oublient.</p> <p>Les années passèrent. Nyambura vieillit. Un soir de grande sécheresse, alors qu'elle marchait seule dans la savane, elle tomba et ne put se relever. Le soleil tapait fort. Il n'y avait personne.</p> <p>Alors un grondement sourd fit trembler la terre. Un grand éléphant s'approcha. Il tendit sa trompe vers Nyambura et l'aida à se relever doucement, comme si ses mains connaissaient sa fragilité. Puis il s'accroupit pour qu'elle puisse monter sur son dos, et la porta jusqu'à son village.</p> <p>C'était Ndovu. Adulte, grand, fort. Il l'avait reconnue. Il n'avait pas oublié.</p> <p>Les dieux de la savane, émus, décidèrent ce soir-là que les éléphants garderaient toujours la mémoire de ceux qui les avaient aidés — et de ceux qu'ils avaient perdus.</p> <p>C'est pour ça que les éléphants retournent sur les os de leurs morts, les touchent de leur trompe, et restent longtemps, longtemps, immobiles — à se souvenir.</p> <p class="tale-closing">— N'oublie jamais qui t'a tendu la main. La mémoire du cœur est la plus précieuse de toutes.</p>`
    },
    "22": {
        titre: "Aminata et le Génie du Fleuve",
        origine: "🌍 Guinée — Tradition Peule",
        morale: "La bonté du cœur est la seule richesse que personne ne peut voler.",
        corps: `<p class="tale-opening">Sur les rives du Niger, les mères peules chantent encore cette chanson à leurs filles : « Aminata, douce Aminata, le fleuve t'a reconnue... »</p> <p class="tale-drop-cap">Aminata et sa sœur Fatou allaient chaque matin chercher de l'eau au bord du grand fleuve. Fatou était belle, mais son cœur était fermé comme un poing. Aminata était simple, mais son sourire éclairait les visages comme une lanterne dans la nuit.</p> <p>Un matin, Aminata trouva au bord de l'eau une petite tortue retournée sur le dos, ses pattes qui agitaient le vide. Elle la remit sur ses pattes doucement et la regarda partir dans les herbes.</p> <p>Le lendemain, un vieillard avec des yeux comme de l'eau verte s'assit près d'elle pendant qu'elle puisait. <span class="dialogue">— Petite, dit-il, je suis le génie de ce fleuve. J'ai vu ta bonté hier. Je te donne un don : quand tu rentres chez toi, va regarder dans ta jarre vide.</span></p> <p>Aminata rentra. Dans sa jarre vide, elle trouva des perles d'or, du tissu de soie et une calebasse remplie de mil qui ne se vidait jamais.</p> <p>Fatou entendit l'histoire. Le lendemain, elle courut au fleuve, trouva la première tortue qu'elle put et la retourna sur le dos. <span class="dialogue">— Voilà, j'ai fait une bonne action ! Maintenant, vieux génie, montre-toi !</span></p> <p>Le génie du fleuve apparut, la regarda longtemps. <span class="dialogue">— Petite, dit-il doucement, une bonne action faite pour une récompense n'est pas une bonne action. C'est un calcul. Va, et apprends à donner sans attendre.</span></p> <p>Fatou rentra les mains vides et le cœur un peu plus ouvert qu'avant.</p> <p class="tale-closing">— Donne parce que c'est juste, pas pour recevoir. Le reste viendra de lui-même.</p>`
    },
    "23": {
        titre: "Le Crocodile et le Petit Chasseur",
        origine: "🌍 Congo — Tradition Kongo",
        morale: "Aider quelqu'un laisse une trace, même dans les cœurs les plus sauvages.",
        corps: `<p class="tale-opening">Au bord du Congo, sous les palétuviers géants, un vieux pêcheur raconte cette histoire à son fils chaque soir avant de dormir...</p> <p class="tale-drop-cap">Un jeune chasseur nommé Luzolo traversait la forêt du Congo quand il entendit des cris au bord de la rivière. Il écarta les lianes et trouva un grand crocodile dont la patte était prise sous un rocher énorme. La bête souffrait et battait l'eau de sa queue.</p> <p>Luzolo hésita. C'était un crocodile. Un crocodile mangeait les hommes. Mais la bête souffrait.</p> <p>Il prit son bâton, fit levier sous le rocher, et libéra la patte du crocodile.</p> <p>Le crocodile se retourna. Ses petits yeux jaunes fixèrent le chasseur. Un long silence.</p> <p>Puis une voix grave comme le fond de la rivière dit : <span class="dialogue">— Pourquoi m'as-tu sauvé ? Tu sais que je mange les hommes.</span></p> <p><span class="dialogue">— Je sais, dit Luzolo. Mais tu souffrais.</span></p> <p>Un autre silence. <span class="dialogue">— Je te dois la vie. Va-t'en vite, avant que ma faim revienne et que j'oublie ma dette.</span></p> <p>Luzolo s'en alla. Mais quelques lunes plus tard, les chasseurs du village organisèrent une chasse au crocodile. Luzolo refusa de participer. <span class="dialogue">— Pas ce crocodile-là, dit-il.</span></p> <p>Les autres chasseurs n'écoutèrent pas. Ils s'approchèrent du fleuve avec leurs lances. Mais le crocodile, depuis sa berge, cria : <span class="dialogue">— Il y a des hippos en amont — bien plus gros et meilleurs à manger !</span> Et les chasseurs partirent de l'autre côté.</p> <p>Ce soir-là, Luzolo vint au bord de l'eau et dit simplement : <span class="dialogue">— Merci.</span> Et le crocodile plongea en silence, laissant derrière lui des cercles dans l'eau dorée du soleil couchant.</p> <p class="tale-closing">— Un bienfait n'est jamais perdu. Même dans les cœurs les plus sauvages, il laisse une trace.</p>`
    },
    "24": {
        titre: "La Sagesse du Vieux Griot",
        origine: "🌍 Mali — Tradition Bambara",
        morale: "Écouter les anciens, c'est apprendre de mille vies en une seule.",
        corps: `<p class="tale-opening">Au Mali, on dit : « Quand un vieux meurt, c'est une bibliothèque qui brûle. » Voici pourquoi...</p> <p class="tale-drop-cap">Dans le village de Ségou, vivait un vieux griot nommé Mamadou Kouyaté. Il avait cent ans — ou peut-être deux cents, personne ne savait vraiment. Sa voix était cassée, ses yeux brumeux, mais quand il commençait à parler, même les chevaux s'arrêtaient de manger.</p> <p>Les jeunes du village ne l'écoutaient plus. <span class="dialogue">— Il raconte toujours les mêmes vieilles histoires, disaient-ils. Nous voulons apprendre des choses nouvelles !</span></p> <p>Un garçon nommé Baba, lui, s'asseyait toujours aux pieds du vieux griot. Les autres se moquaient de lui.</p> <p>Un jour, la rivière changea de cours et inonda les champs. Les anciens du village étaient désemparés. Les jeunes proposèrent de creuser un nouveau canal — ce qui aurait pris des années et détruit la forêt.</p> <p>Mamadou Kouyaté leva sa main ridée. <span class="dialogue">— Cela est déjà arrivé, dit-il. Il y a soixante-dix ans. Nous avions planté des bambous en arc de cercle en amont. Ils ont dévié la rivière en trois saisons.</span></p> <p>Baba avait entendu cette histoire. Il courut chercher des bambous. On planta. On attendit. Et la rivière, trois saisons plus tard, reprit son ancien lit.</p> <p>Le village entier vint s'asseoir aux pieds du vieux griot. <span class="dialogue">— Comment sais-tu tout cela ? lui demanda-t-on.</span></p> <p><span class="dialogue">— Parce que j'ai écouté le vieux griot qui était là avant moi, dit Mamadou. Et lui avait écouté celui d'avant. C'est comme ça que fonctionne la sagesse — elle se passe comme un flambeau. Si personne ne tend la main, le feu s'éteint.</span></p> <p>Cette nuit-là, tous les jeunes du village s'assirent autour du feu, et Mamadou Kouyaté parla jusqu'à l'aube.</p> <p class="tale-closing">— Écoutez vos grands-parents. Ils ont des trésors dans la voix qu'aucun livre ne peut contenir.</p>`
    },
    "25": {
        titre: "Nana Buluku et la Naissance du Monde",
        origine: "🌍 Bénin — Tradition Fon",
        morale: "Nous sommes tous reliés à la terre et aux étoiles. Prendre soin du monde, c'est prendre soin de soi.",
        corps: `<p class="tale-opening">Au commencement, dit-on dans le peuple Fon du Bénin, il n'y avait ni lumière, ni terre, ni ciel — seulement Nana Buluku, la mère de tout...</p> <p class="tale-drop-cap">Nana Buluku était avant tout. Elle n'avait ni début ni fin, comme un cercle parfait. Elle portait en elle deux enfants jumeaux : Mawu la lune, douce et sage, et Lisa le soleil, fort et ardent. Un jour, lasse de porter tout le monde en elle, elle souffla.</p> <p>Ce souffle créa l'espace.</p> <p>Elle souffla une deuxième fois. Ce souffle créa la lumière et l'obscurité — le jour et la nuit, Mawu et Lisa qui se mirent à tourner l'un autour de l'autre comme deux danseurs.</p> <p>Mais la Terre n'existait pas encore. Alors Nana Buluku prit une graine de sa paume — une graine minuscule et brune, pas plus grande qu'un grain de sable — et la planta dans l'obscurité.</p> <p>La graine grandit. Elle devint une montagne, puis un continent, puis la Terre entière, avec ses forêts, ses rivières, ses savanes et ses océans. Les animaux sortirent de la terre comme des fleurs — les éléphants, les oiseaux, les poissons, les insectes.</p> <p>Puis Mawu, la lune, prit de la poussière de terre rouge, de l'eau des premiers fleuves et un peu du souffle de Nana Buluku — et façonna les premiers hommes et les premières femmes. Elle les mit debout et leur insuffla la vie.</p> <p>Les premiers hommes regardèrent autour d'eux, éblouis. <span class="dialogue">— Qui a fait tout cela ? demandèrent-ils.</span></p> <p>La voix de Nana Buluku résonna dans le vent et dans les arbres : <span class="dialogue">— Vous êtes faits de la même poussière que les étoiles, de la même eau que les fleuves, du même souffle que le vent. Vous n'êtes pas séparés du monde — vous en êtes une partie. Prenez-en soin comme vous prendriez soin de vous-mêmes.</span></p> <p>Et depuis ce jour, quand la nuit tombe sur le Bénin et que la lune Mawu monte dans le ciel, les enfants lèvent les yeux et savent qu'ils regardent leur mère — et que quelque part, dans le souffle du vent entre les palmiers, Nana Buluku veille encore.</p>
       <p class="tale-closing">— Vous portez en vous l'étoile, la rivière et la terre. Prenez-en grand soin. 
       
       <br>✨ Fin des contes ✨</p> `
    }
};
